config/routes.rb
SimpleIssueTracker::Application.routes.draw do
  devise_for :users

  root 'issues#new'

  resources :issues, only: [:new, :create, :show, :index] do
    resources :comments, only: [:create]
    get :take_ownership
    get :fire
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :issue
  belongs_to :user

  validates :content, presence: true

  after_save :update_issue_state
  after_save :notify_customer

  def from_customer?
    user.blank?
  end

  private

  def update_issue_state
    issue.update_state_by_last_comment
  end

  def notify_customer
    IssueMailer.new_comment_email(self).deliver
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include AASM

  belongs_to :department
  has_many :comments

  validates :customer_name, :content, presence: true
  validates :customer_email, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :state, inclusion: { in: %w(waiting_for_staff_response waiting_for_customer on_hold cancelled completed) }

  belongs_to :user
  belongs_to :department

  scope :unassigned, -> { where('issues.user_id is null') }
  scope :by_user, -> (user) { where(user_id: user) }

  scope :open, -> { where(state: [:waiting_for_staff_response, :waiting_for_customer]) }
  scope :closed, -> { where(state: [:cancelled, :completed]) }

  def open?
    %w(waiting_for_staff_response waiting_for_customer).include?(state)
  end

  def closed?
    %w(cancelled completed).include?(state)
  end

  def update_state_by_last_comment
    if open? && (last_comment = comments.last)
      update_attribute(:state, last_comment.from_customer? ? :waiting_for_staff_response : :waiting_for_customer)
    end
  end

  def self.by_filter(filter)
    case filter
    when 'new_unassigned_items'
      open.unassigned
    when 'open_tickets'
      open
    when 'on_hold_tickets'
      on_hold
    when 'closed_tickets'
      closed
    else
      where(nil)
    end
  end

  aasm column: :state do 
    state :waiting_for_staff_response, initial: true
    state :waiting_for_customer 
    state :on_hold 
    state :cancelled 
    state :completed

    event :cancel do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer, :on_hold], to: :cancelled
    end

    event :complete do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer, :on_hold], to: :completed
    end

    event :hold do
      transitions from: [:waiting_for_staff_response, :waiting_for_customer], to: :on_hold
    end

    event :unhold do
      after do
        update_state_by_last_comment
      end
      transitions from: :on_hold, to: :waiting_for_staff_response
    end
  end

  def take_ownership!(user)
    update_attribute(:user_id, user.id)
  end

  def fire!(event)
    if %w(cancel complete hold unhold).include? event
      send("#{event}!")
    end
  end

  def owned_by?(user)
    self.user.try(:id) == user.id
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  validate :validate_ip_address

  def allowed_for_ip?(ip)
    if allowed_ip_address.present?
      from, to = allowed_ip_address.split('-')
      range = if to.present?
                IPAddr.new(from)..IPAddr.new(to)
              else
                IPAddr.new(from).to_range
              end
      range.include?(ip)
    else
      true
    end
  end

  private

  def validate_ip_address
    if allowed_ip_address.present?
      from, to = allowed_ip_address.split('-')
      begin
        IPAddr.new(from)
      rescue
        errors.add(:allowed_ip_address, 'Invalid address')
      end
      begin
        ip_to = IPAddr.new(to)
      rescue
        errors.add(:allowed_ip_address, 'Invalid address')
      end
      if ip_to.present? && (ip_from.to_range > 1 || ip_from.to_range > 1)
        errors.add(:allowed_ip_address, 'Invalid address')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :validate_ip

  private

  def validate_ip
    if signed_in?
      head 403 unless current_user.allowed_for_ip?(request.ip)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_issue, only: [:create]

  def create
    @comment = @issue.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @issue }
      else
        format.html { render 'issues/show' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:issue_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment].permit(:content)
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :take_ownership, :fire]
  before_action :authenticate_user!, only: [:index, :take_ownership, :fire]

  def index
    @filter = params[:filter]
    @issues = Issue.by_filter(@filter).order(id: :desc)
  end

  def show
    @comment = Comment.new(issue: @issue)
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def take_ownership
    @issue.take_ownership!(current_user)
    p @issue
    respond_to do |format|
      format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
    end
  end

  def fire
    respond_to do |format|
      if @issue.owned_by?(current_user)
        @issue.fire!(params[:event])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
      else
        format.html { render status: :not_found }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id] || params[:issue_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params[:issue].permit(:customer_name, :customer_email, :content, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def describe_user(user)
    user.try(:email)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def describe_comment_author(comment)
    describe_user(comment.user) || comment.issue.customer_name
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def issue_filter_options
    options_for_select(%w{new_unassigned_items open_tickets on_hold_tickets closed_tickets}.
                       inject([]) { |r, i| r << [i.humanize, i, {'data-url' => issues_path(filter: i)}] }, @filter)
  end
end

app/views/comments/_form.html.haml
= form_for [@issue, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  .fieldset
    .field
      = f.label :content
      = f.text_area :content
  .actions
    = f.submit 'Submit'

app/views/comments/_index.html.haml
%h1 Comments

%table
  - comments.each do |comment|
    %tr
      %th= describe_comment_author(comment)
      %th
        at
        = comment.created_at
    %tr
      %td= h simple_format(comment.content)

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/issues/_form.html.haml
= form_for @issue do |f|
  - if @issue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg
  .fieldset
    .field
      = f.label :customer_name
      = f.text_field :customer_name
    .field
      = f.label :customer_email
      = f.text_field :customer_email
    .field
      = f.label :department_id, 'Department'
      = f.collection_select :department_id, Department.all, :id, :name, prompt: '-- select one --'
    .field
      = f.label :content, 'Description'
      = f.text_area :content
  .actions
    = f.submit 'Submit'

app/views/issues/edit.html.haml
%h1 Editing issue

= render 'form'

= link_to 'Show', @issue
\|
= link_to 'Back', issues_path

app/views/issues/index.html.haml
%h1 Listing issues
= label_tag 'Show'
= select_tag :filter, issue_filter_options, onchange: 'window.location = $(this).find("option:selected").data("url")', include_blank: true

%table
  %tr
    %th Customer Name
    %th Customer Email
    %th Owner
    %th Department
    %th State
    %th Created At
  - @issues.each do |issue|
    %tr
      %td= issue.customer_name
      %td= issue.customer_email
      %td= describe_user(issue.user)
      %td= issue.department.try(:name)
      %td= issue.state.humanize
      %td= issue.created_at
      %td= link_to 'Show', issue

%br

= link_to 'New Issue', new_issue_path

app/views/issues/new.html.haml
%h1 New issue

= render 'form'
- if signed_in?
  = link_to 'Back to issues', issues_path

app/views/issues/show.html.haml
%br
= link_to 'New Issue', new_issue_path
%p#notice= notice

%table
  - if signed_in?
    %tr
      %td Owner
      %td#owner_container= describe_user(@issue.user)
    %tr
      %th Actions
      %td
        - if @issue.owned_by?(current_user)
          - @issue.aasm.events.each do |event|
            = link_to event.to_s.humanize, issue_fire_path(@issue, event: event)
        - else
          = link_to 'Take ownership', issue_take_ownership_path(@issue)
  %tr
    %th Issue #
    %td= @issue.id
  %tr
    %th Customer Name
    %td= @issue.customer_name
  %tr
    %th Customer Email
    %td= @issue.customer_email
  %tr
    %th Department
    %td= @issue.department.try(:name)
  %tr
    %th State
    %td#state_container= @issue.state.to_s.humanize
  %tr
    %th Created At
    %td= @issue.created_at
  %tr
    %th Description
    %td= h simple_format(@issue.content)
- if signed_in?
  = link_to 'Back to Issues', issues_path
#comments
  = render 'comments/index', comments: @issue.comments
#new_comment
  %h3 New comment
  = render 'comments/form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleIssueTracker
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #login_menu
    - if user_signed_in?
      Welcome, #{describe_user(current_user)}
      = link_to 'Logout', destroy_user_session_path, method: :delete
    - else
      = link_to 'Login', new_user_session_path
    = yield